spring:
  application:
    name: customer-ms
  data:
    mongodb:
     host: localhost
     port: 27017
     database: nullbeans
     username: suruchi
     password: suruchi
server:
  port: 5454
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
 